services:
  ml-rpg:
    container_name: ml-rpg
    image: swang62/ml-rpg
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT:-3333}:${PORT:-3333}
    volumes:
      - course-data:/app/.data
    environment:
      - COURSE_DB_PATH=${COURSE_DB_PATH:-./.data/course.db}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - LANCEDB_PATH=${LANCEDB_PATH:-./.data/search}
      - PORT=${PORT:-3333}
      - SESSION_SECRET=${SESSION_SECRET}
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}

volumes:
  course-data:
