services:
  ml-rpg:
    container_name: ml-rpg
    image: swang62/ml-rpg
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - ${PORT:-3333}:${PORT:-3333}
    volumes:
      - course-data:/app/.data
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=${PORT:-3333}
      - COURSE_DB_PATH=/app/.data/course.db
      - LANCEDB_PATH=/app/.data/search
      - VOYAGE_API_KEY=${VOYAGE_API_KEY}
      - GROQ_API_KEY=${GROQ_API_KEY}

volumes:
  course-data:
