fine_tune_type: lora
optimizer: adamw
optimizer_config:
  adamw:
    weight_decay: 0.05
iters: 100
steps_per_eval: 50
learning_rate: 1.5e-5
batch_size: 4
num_layers: 28
lora_parameters:
  rank: 8
  dropout: 0.1
  scale: 8.0
