fine_tune_type: lora
optimizer: adamw
optimizer_config:
  adamw:
    weight_decay: 0.01
iters: 120
steps_per_eval: 40
learning_rate: 2e-5
batch_size: 8
num_layers: 28
lora_parameters:
  rank: 8
  dropout: 0.1
  scale: 8.0
