minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@cloudflare/workerd-darwin-64"
  - "@cloudflare/workerd-darwin-arm64"
  - "@cloudflare/workerd-linux-64"
  - "@cloudflare/workerd-linux-arm64"
  - "@cloudflare/workerd-windows-64"
  - miniflare
  - workerd
  - wrangler

allowBuilds:
  "@parcel/watcher": true
  argon2: true
  better-sqlite3: true
  esbuild: true
  sharp: false
  workerd: false
