// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const ensureCourseTableQuery = `-- name: EnsureCourseTable :exec
CREATE TABLE IF NOT EXISTS course (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL
)`;

export async function ensureCourseTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureCourseTableQuery);
    await stmt.run();
}

export const ensureCategoryTableQuery = `-- name: EnsureCategoryTable :exec
CREATE TABLE IF NOT EXISTS category (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  course_id INTEGER NOT NULL REFERENCES course(id),
  UNIQUE(course_id, slug)
)`;

export async function ensureCategoryTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureCategoryTableQuery);
    await stmt.run();
}

export const ensureSectionTableQuery = `-- name: EnsureSectionTable :exec
CREATE TABLE IF NOT EXISTS section (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  course_id INTEGER NOT NULL REFERENCES course(id),
  category_id INTEGER NOT NULL REFERENCES category(id),
  UNIQUE(course_id, category_id, slug)
)`;

export async function ensureSectionTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureSectionTableQuery);
    await stmt.run();
}

export const ensureLessonTableQuery = `-- name: EnsureLessonTable :exec
CREATE TABLE IF NOT EXISTS lesson (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  html TEXT NOT NULL DEFAULT '',
  lesson_order INTEGER NOT NULL DEFAULT 0,
  course_id INTEGER NOT NULL REFERENCES course(id),
  category_id INTEGER NOT NULL REFERENCES category(id),
  section_id INTEGER NOT NULL REFERENCES section(id),
  UNIQUE(course_id, category_id, section_id, slug)
)`;

export async function ensureLessonTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureLessonTableQuery);
    await stmt.run();
}

export const ensureUsersTableQuery = `-- name: EnsureUsersTable :exec
CREATE TABLE IF NOT EXISTS users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  user_password TEXT NOT NULL,
  display_name TEXT
)`;

export async function ensureUsersTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureUsersTableQuery);
    await stmt.run();
}

export const ensureProgressTableQuery = `-- name: EnsureProgressTable :exec
CREATE TABLE IF NOT EXISTS progress (
  lesson_id INTEGER NOT NULL REFERENCES lesson(id),
  user_id INTEGER NOT NULL REFERENCES users(id),
  read_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (lesson_id, user_id)
)`;

export async function ensureProgressTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureProgressTableQuery);
    await stmt.run();
}

