// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getCategoriesByCourseQuery = `-- name: GetCategoriesByCourse :many
SELECT category.id, category.slug, category.title FROM category WHERE category.course_id = ?`;

export interface GetCategoriesByCourseArgs {
    courseId: any;
}

export interface GetCategoriesByCourseRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCategoriesByCourse(database: Database, args: GetCategoriesByCourseArgs): Promise<GetCategoriesByCourseRow[]> {
    const stmt = database.prepare(getCategoriesByCourseQuery);
    const result = await stmt.all(args.courseId);
    return result as GetCategoriesByCourseRow[];
}

export const getCategoryLessonCountsQuery = `-- name: GetCategoryLessonCounts :many
SELECT category.slug AS categoryslug, COUNT(lesson.id) AS lessoncount
FROM category
INNER JOIN lesson ON lesson.category_id = category.id
WHERE category.course_id = ?
GROUP BY category.id`;

export interface GetCategoryLessonCountsArgs {
    courseId: any;
}

export interface GetCategoryLessonCountsRow {
    categoryslug: any;
    lessoncount: number;
}

export async function getCategoryLessonCounts(database: Database, args: GetCategoryLessonCountsArgs): Promise<GetCategoryLessonCountsRow[]> {
    const stmt = database.prepare(getCategoryLessonCountsQuery);
    const result = await stmt.all(args.courseId);
    return result as GetCategoryLessonCountsRow[];
}

export const getAllCategoriesQuery = `-- name: GetAllCategories :many
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category`;

export interface GetAllCategoriesRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
}

export async function getAllCategories(database: Database): Promise<GetAllCategoriesRow[]> {
    const stmt = database.prepare(getAllCategoriesQuery);
    const result = await stmt.all();
    return result as GetAllCategoriesRow[];
}

export const getCategoryByIdQuery = `-- name: GetCategoryById :one
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category WHERE category.id = ?`;

export interface GetCategoryByIdArgs {
    id: any;
}

export interface GetCategoryByIdRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
}

export async function getCategoryById(database: Database, args: GetCategoryByIdArgs): Promise<GetCategoryByIdRow | null> {
    const stmt = database.prepare(getCategoryByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetCategoryByIdRow;
}

export const getCategoryBySlugQuery = `-- name: GetCategoryBySlug :one
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category WHERE category.slug = ? AND category.course_id = ?`;

export interface GetCategoryBySlugArgs {
    slug: any;
    courseId: any;
}

export interface GetCategoryBySlugRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
}

export async function getCategoryBySlug(database: Database, args: GetCategoryBySlugArgs): Promise<GetCategoryBySlugRow | null> {
    const stmt = database.prepare(getCategoryBySlugQuery);
    const result = await stmt.get(args.slug, args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as GetCategoryBySlugRow;
}

export const createCategoryQuery = `-- name: CreateCategory :one
INSERT INTO category (slug, title, course_id) VALUES (?, ?, ?) RETURNING id`;

export interface CreateCategoryArgs {
    slug: any;
    title: any;
    courseId: any;
}

export interface CreateCategoryRow {
    id: any;
}

export async function createCategory(database: Database, args: CreateCategoryArgs): Promise<CreateCategoryRow | null> {
    const stmt = database.prepare(createCategoryQuery);
    const result = await stmt.get(args.slug, args.title, args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as CreateCategoryRow;
}

export const deleteAllCategoriesQuery = `-- name: DeleteAllCategories :exec
DELETE FROM category`;

export async function deleteAllCategories(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllCategoriesQuery);
    await stmt.run();
}

