// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getCourseByIdQuery = `-- name: GetCourseById :one
SELECT course.id, course.slug, course.title FROM course WHERE course.id = ?`;

export interface GetCourseByIdArgs {
    id: any;
}

export interface GetCourseByIdRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCourseById(database: Database, args: GetCourseByIdArgs): Promise<GetCourseByIdRow | null> {
    const stmt = database.prepare(getCourseByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetCourseByIdRow;
}

export const getCourseBySlugQuery = `-- name: GetCourseBySlug :one
SELECT course.id, course.slug, course.title FROM course WHERE course.slug = ?`;

export interface GetCourseBySlugArgs {
    slug: any;
}

export interface GetCourseBySlugRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCourseBySlug(database: Database, args: GetCourseBySlugArgs): Promise<GetCourseBySlugRow | null> {
    const stmt = database.prepare(getCourseBySlugQuery);
    const result = await stmt.get(args.slug);
    if (result == undefined) {
        return null;
    }
    return result as GetCourseBySlugRow;
}

export const getCategoriesByCourseQuery = `-- name: GetCategoriesByCourse :many
SELECT category.id, category.slug, category.title FROM category WHERE category.course_id = ?`;

export interface GetCategoriesByCourseArgs {
    courseId: any;
}

export interface GetCategoriesByCourseRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCategoriesByCourse(database: Database, args: GetCategoriesByCourseArgs): Promise<GetCategoriesByCourseRow[]> {
    const stmt = database.prepare(getCategoriesByCourseQuery);
    const result = await stmt.all(args.courseId);
    return result as GetCategoriesByCourseRow[];
}

export const getCategoryByIdQuery = `-- name: GetCategoryById :one
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category WHERE category.id = ?`;

export interface GetCategoryByIdArgs {
    id: any;
}

export interface GetCategoryByIdRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
}

export async function getCategoryById(database: Database, args: GetCategoryByIdArgs): Promise<GetCategoryByIdRow | null> {
    const stmt = database.prepare(getCategoryByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetCategoryByIdRow;
}

export const getCategoryBySlugQuery = `-- name: GetCategoryBySlug :one
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category WHERE category.slug = ? AND category.course_id = ?`;

export interface GetCategoryBySlugArgs {
    slug: any;
    courseId: any;
}

export interface GetCategoryBySlugRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
}

export async function getCategoryBySlug(database: Database, args: GetCategoryBySlugArgs): Promise<GetCategoryBySlugRow | null> {
    const stmt = database.prepare(getCategoryBySlugQuery);
    const result = await stmt.get(args.slug, args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as GetCategoryBySlugRow;
}

export const getSectionsByCategoryQuery = `-- name: GetSectionsByCategory :many
SELECT section.id, section.slug, section.title FROM section WHERE section.category_id = ?`;

export interface GetSectionsByCategoryArgs {
    categoryId: any;
}

export interface GetSectionsByCategoryRow {
    id: any;
    slug: any;
    title: any;
}

export async function getSectionsByCategory(database: Database, args: GetSectionsByCategoryArgs): Promise<GetSectionsByCategoryRow[]> {
    const stmt = database.prepare(getSectionsByCategoryQuery);
    const result = await stmt.all(args.categoryId);
    return result as GetSectionsByCategoryRow[];
}

export const getSectionByIdQuery = `-- name: GetSectionById :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid FROM section WHERE section.id = ?`;

export interface GetSectionByIdArgs {
    id: any;
}

export interface GetSectionByIdRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
    categoryid: any;
}

export async function getSectionById(database: Database, args: GetSectionByIdArgs): Promise<GetSectionByIdRow | null> {
    const stmt = database.prepare(getSectionByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetSectionByIdRow;
}

export const getSectionBySlugQuery = `-- name: GetSectionBySlug :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid FROM section WHERE section.slug = ? AND section.category_id = ?`;

export interface GetSectionBySlugArgs {
    slug: any;
    categoryId: any;
}

export interface GetSectionBySlugRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
    categoryid: any;
}

export async function getSectionBySlug(database: Database, args: GetSectionBySlugArgs): Promise<GetSectionBySlugRow | null> {
    const stmt = database.prepare(getSectionBySlugQuery);
    const result = await stmt.get(args.slug, args.categoryId);
    if (result == undefined) {
        return null;
    }
    return result as GetSectionBySlugRow;
}

export const getLessonsBySectionQuery = `-- name: GetLessonsBySection :many
SELECT lesson.id, lesson.slug, lesson.title, lesson."order" FROM lesson WHERE lesson.section_id = ? ORDER BY lesson."order"`;

export interface GetLessonsBySectionArgs {
    sectionId: any;
}

export interface GetLessonsBySectionRow {
    id: any;
    slug: any;
    title: any;
    order: any;
}

export async function getLessonsBySection(database: Database, args: GetLessonsBySectionArgs): Promise<GetLessonsBySectionRow[]> {
    const stmt = database.prepare(getLessonsBySectionQuery);
    const result = await stmt.all(args.sectionId);
    return result as GetLessonsBySectionRow[];
}

export const getLessonByIdQuery = `-- name: GetLessonById :one
SELECT lesson.id, lesson.slug, lesson.title, lesson."order", lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson WHERE lesson.id = ?`;

export interface GetLessonByIdArgs {
    id: any;
}

export interface GetLessonByIdRow {
    id: any;
    slug: any;
    title: any;
    order: any;
    sectionid: any;
    categoryid: any;
    courseid: any;
}

export async function getLessonById(database: Database, args: GetLessonByIdArgs): Promise<GetLessonByIdRow | null> {
    const stmt = database.prepare(getLessonByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetLessonByIdRow;
}

export const getLessonBySlugQuery = `-- name: GetLessonBySlug :one
SELECT lesson.id, lesson.slug, lesson.title, lesson."order", lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson WHERE lesson.slug = ? AND lesson.section_id = ?`;

export interface GetLessonBySlugArgs {
    slug: any;
    sectionId: any;
}

export interface GetLessonBySlugRow {
    id: any;
    slug: any;
    title: any;
    order: any;
    sectionid: any;
    categoryid: any;
    courseid: any;
}

export async function getLessonBySlug(database: Database, args: GetLessonBySlugArgs): Promise<GetLessonBySlugRow | null> {
    const stmt = database.prepare(getLessonBySlugQuery);
    const result = await stmt.get(args.slug, args.sectionId);
    if (result == undefined) {
        return null;
    }
    return result as GetLessonBySlugRow;
}

export const getAllLessonsQuery = `-- name: GetAllLessons :many
SELECT lesson.id, lesson.slug, lesson.title, lesson."order", lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson`;

export interface GetAllLessonsRow {
    id: any;
    slug: any;
    title: any;
    order: any;
    sectionid: any;
    categoryid: any;
    courseid: any;
}

export async function getAllLessons(database: Database): Promise<GetAllLessonsRow[]> {
    const stmt = database.prepare(getAllLessonsQuery);
    const result = await stmt.all();
    return result as GetAllLessonsRow[];
}

export const createCourseQuery = `-- name: CreateCourse :one
INSERT INTO course (slug, title) VALUES (?, ?) RETURNING id`;

export interface CreateCourseArgs {
    slug: any;
    title: any;
}

export interface CreateCourseRow {
    id: any;
}

export async function createCourse(database: Database, args: CreateCourseArgs): Promise<CreateCourseRow | null> {
    const stmt = database.prepare(createCourseQuery);
    const result = await stmt.get(args.slug, args.title);
    if (result == undefined) {
        return null;
    }
    return result as CreateCourseRow;
}

export const createCategoryQuery = `-- name: CreateCategory :one
INSERT INTO category (slug, title, course_id) VALUES (?, ?, ?) RETURNING id`;

export interface CreateCategoryArgs {
    slug: any;
    title: any;
    courseId: any;
}

export interface CreateCategoryRow {
    id: any;
}

export async function createCategory(database: Database, args: CreateCategoryArgs): Promise<CreateCategoryRow | null> {
    const stmt = database.prepare(createCategoryQuery);
    const result = await stmt.get(args.slug, args.title, args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as CreateCategoryRow;
}

export const createSectionQuery = `-- name: CreateSection :one
INSERT INTO section (slug, title, course_id, category_id) VALUES (?, ?, ?, ?) RETURNING id`;

export interface CreateSectionArgs {
    slug: any;
    title: any;
    courseId: any;
    categoryId: any;
}

export interface CreateSectionRow {
    id: any;
}

export async function createSection(database: Database, args: CreateSectionArgs): Promise<CreateSectionRow | null> {
    const stmt = database.prepare(createSectionQuery);
    const result = await stmt.get(args.slug, args.title, args.courseId, args.categoryId);
    if (result == undefined) {
        return null;
    }
    return result as CreateSectionRow;
}

export const createLessonQuery = `-- name: CreateLesson :one
INSERT INTO lesson (slug, title, html, "order", course_id, category_id, section_id) VALUES (?, ?, ?, ?, ?, ?, ?) RETURNING id`;

export interface CreateLessonArgs {
    slug: any;
    title: any;
    html: any;
    order: any;
    courseId: any;
    categoryId: any;
    sectionId: any;
}

export interface CreateLessonRow {
    id: any;
}

export async function createLesson(database: Database, args: CreateLessonArgs): Promise<CreateLessonRow | null> {
    const stmt = database.prepare(createLessonQuery);
    const result = await stmt.get(args.slug, args.title, args.html, args.order, args.courseId, args.categoryId, args.sectionId);
    if (result == undefined) {
        return null;
    }
    return result as CreateLessonRow;
}

export const deleteAllCoursesQuery = `-- name: DeleteAllCourses :exec
DELETE FROM course`;

export async function deleteAllCourses(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllCoursesQuery);
    await stmt.run();
}

export const deleteAllCategoriesQuery = `-- name: DeleteAllCategories :exec
DELETE FROM category`;

export async function deleteAllCategories(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllCategoriesQuery);
    await stmt.run();
}

export const deleteAllSectionsQuery = `-- name: DeleteAllSections :exec
DELETE FROM section`;

export async function deleteAllSections(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllSectionsQuery);
    await stmt.run();
}

export const deleteAllLessonsQuery = `-- name: DeleteAllLessons :exec
DELETE FROM lesson`;

export async function deleteAllLessons(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllLessonsQuery);
    await stmt.run();
}

export const getLessonCountQuery = `-- name: GetLessonCount :one
SELECT COUNT(*) AS lessoncount FROM lesson`;

export interface GetLessonCountRow {
    lessoncount: number;
}

export async function getLessonCount(database: Database): Promise<GetLessonCountRow | null> {
    const stmt = database.prepare(getLessonCountQuery);
    const result = await stmt.get();
    if (result == undefined) {
        return null;
    }
    return result as GetLessonCountRow;
}

