// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getCourseQuery = `-- name: GetCourse :one
SELECT course.course_id, course.slug, course.title FROM course WHERE course.course_id = ?`;

export interface GetCourseArgs {
    courseId: any;
}

export interface GetCourseRow {
    courseId: any;
    slug: any;
    title: any;
}

export async function getCourse(database: Database, args: GetCourseArgs): Promise<GetCourseRow | null> {
    const stmt = database.prepare(getCourseQuery);
    const result = await stmt.get(args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as GetCourseRow;
}

export const getCourseBySlugQuery = `-- name: GetCourseBySlug :one
SELECT course.course_id, course.slug, course.title FROM course WHERE course.slug = ?`;

export interface GetCourseBySlugArgs {
    slug: any;
}

export interface GetCourseBySlugRow {
    courseId: any;
    slug: any;
    title: any;
}

export async function getCourseBySlug(database: Database, args: GetCourseBySlugArgs): Promise<GetCourseBySlugRow | null> {
    const stmt = database.prepare(getCourseBySlugQuery);
    const result = await stmt.get(args.slug);
    if (result == undefined) {
        return null;
    }
    return result as GetCourseBySlugRow;
}

export const getCategoriesByCourseQuery = `-- name: GetCategoriesByCourse :many
SELECT category.category_id, category.slug, category.title FROM category WHERE category.course_id = ?`;

export interface GetCategoriesByCourseArgs {
    courseId: any;
}

export interface GetCategoriesByCourseRow {
    categoryId: any;
    slug: any;
    title: any;
}

export async function getCategoriesByCourse(database: Database, args: GetCategoriesByCourseArgs): Promise<GetCategoriesByCourseRow[]> {
    const stmt = database.prepare(getCategoriesByCourseQuery);
    const result = await stmt.all(args.courseId);
    return result as GetCategoriesByCourseRow[];
}

export const getCategoryQuery = `-- name: GetCategory :one
SELECT category.title FROM category WHERE category.category_id = ? AND category.course_id = ?`;

export interface GetCategoryArgs {
    categoryId: any;
    courseId: any;
}

export interface GetCategoryRow {
    title: any;
}

export async function getCategory(database: Database, args: GetCategoryArgs): Promise<GetCategoryRow | null> {
    const stmt = database.prepare(getCategoryQuery);
    const result = await stmt.get(args.categoryId, args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as GetCategoryRow;
}

export const getSectionsByCategoryQuery = `-- name: GetSectionsByCategory :many
SELECT section.section_id, section.slug, section.title FROM section WHERE section.category_id = ?`;

export interface GetSectionsByCategoryArgs {
    categoryId: any;
}

export interface GetSectionsByCategoryRow {
    sectionId: any;
    slug: any;
    title: any;
}

export async function getSectionsByCategory(database: Database, args: GetSectionsByCategoryArgs): Promise<GetSectionsByCategoryRow[]> {
    const stmt = database.prepare(getSectionsByCategoryQuery);
    const result = await stmt.all(args.categoryId);
    return result as GetSectionsByCategoryRow[];
}

export const getSectionQuery = `-- name: GetSection :one
SELECT section.title FROM section WHERE section.section_id = ? AND section.category_id = ? AND section.course_id = ?`;

export interface GetSectionArgs {
    sectionId: any;
    categoryId: any;
    courseId: any;
}

export interface GetSectionRow {
    title: any;
}

export async function getSection(database: Database, args: GetSectionArgs): Promise<GetSectionRow | null> {
    const stmt = database.prepare(getSectionQuery);
    const result = await stmt.get(args.sectionId, args.categoryId, args.courseId);
    if (result == undefined) {
        return null;
    }
    return result as GetSectionRow;
}

export const getLessonsBySectionQuery = `-- name: GetLessonsBySection :many
SELECT lesson.lesson_id, lesson.slug, lesson.title, lesson."order" FROM lesson WHERE lesson.section_id = ? ORDER BY lesson."order"`;

export interface GetLessonsBySectionArgs {
    sectionId: any;
}

export interface GetLessonsBySectionRow {
    lessonId: any;
    slug: any;
    title: any;
    order: any;
}

export async function getLessonsBySection(database: Database, args: GetLessonsBySectionArgs): Promise<GetLessonsBySectionRow[]> {
    const stmt = database.prepare(getLessonsBySectionQuery);
    const result = await stmt.all(args.sectionId);
    return result as GetLessonsBySectionRow[];
}

export const getLessonByIdQuery = `-- name: GetLessonById :one
SELECT lesson.lesson_id, lesson.slug, lesson.title, lesson."order", lesson.section_id, lesson.category_id, lesson.course_id FROM lesson WHERE lesson.lesson_id = ?`;

export interface GetLessonByIdArgs {
    lessonId: any;
}

export interface GetLessonByIdRow {
    lessonId: any;
    slug: any;
    title: any;
    order: any;
    sectionId: any;
    categoryId: any;
    courseId: any;
}

export async function getLessonById(database: Database, args: GetLessonByIdArgs): Promise<GetLessonByIdRow | null> {
    const stmt = database.prepare(getLessonByIdQuery);
    const result = await stmt.get(args.lessonId);
    if (result == undefined) {
        return null;
    }
    return result as GetLessonByIdRow;
}

export const getAllLessonsQuery = `-- name: GetAllLessons :many
SELECT lesson.lesson_id, lesson.slug, lesson.title, lesson."order", lesson.section_id, lesson.category_id, lesson.course_id FROM lesson`;

export interface GetAllLessonsRow {
    lessonId: any;
    slug: any;
    title: any;
    order: any;
    sectionId: any;
    categoryId: any;
    courseId: any;
}

export async function getAllLessons(database: Database): Promise<GetAllLessonsRow[]> {
    const stmt = database.prepare(getAllLessonsQuery);
    const result = await stmt.all();
    return result as GetAllLessonsRow[];
}

export const createCourseQuery = `-- name: CreateCourse :exec
INSERT INTO course (course_id, slug, title) VALUES (?, ?, ?)`;

export interface CreateCourseArgs {
    courseId: any;
    slug: any;
    title: any;
}

export async function createCourse(database: Database, args: CreateCourseArgs): Promise<void> {
    const stmt = database.prepare(createCourseQuery);
    await stmt.run(args.courseId, args.slug, args.title);
}

export const createCategoryQuery = `-- name: CreateCategory :exec
INSERT INTO category (category_id, slug, title, course_id) VALUES (?, ?, ?, ?)`;

export interface CreateCategoryArgs {
    categoryId: any;
    slug: any;
    title: any;
    courseId: any;
}

export async function createCategory(database: Database, args: CreateCategoryArgs): Promise<void> {
    const stmt = database.prepare(createCategoryQuery);
    await stmt.run(args.categoryId, args.slug, args.title, args.courseId);
}

export const createSectionQuery = `-- name: CreateSection :exec
INSERT INTO section (section_id, slug, title, course_id, category_id) VALUES (?, ?, ?, ?, ?)`;

export interface CreateSectionArgs {
    sectionId: any;
    slug: any;
    title: any;
    courseId: any;
    categoryId: any;
}

export async function createSection(database: Database, args: CreateSectionArgs): Promise<void> {
    const stmt = database.prepare(createSectionQuery);
    await stmt.run(args.sectionId, args.slug, args.title, args.courseId, args.categoryId);
}

export const createLessonQuery = `-- name: CreateLesson :exec
INSERT INTO lesson (lesson_id, slug, title, html, "order", course_id, category_id, section_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`;

export interface CreateLessonArgs {
    lessonId: any;
    slug: any;
    title: any;
    html: any;
    order: any;
    courseId: any;
    categoryId: any;
    sectionId: any;
}

export async function createLesson(database: Database, args: CreateLessonArgs): Promise<void> {
    const stmt = database.prepare(createLessonQuery);
    await stmt.run(args.lessonId, args.slug, args.title, args.html, args.order, args.courseId, args.categoryId, args.sectionId);
}

export const deleteAllCoursesQuery = `-- name: DeleteAllCourses :exec
DELETE FROM course`;

export async function deleteAllCourses(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllCoursesQuery);
    await stmt.run();
}

export const deleteAllCategoriesQuery = `-- name: DeleteAllCategories :exec
DELETE FROM category`;

export async function deleteAllCategories(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllCategoriesQuery);
    await stmt.run();
}

export const deleteAllSectionsQuery = `-- name: DeleteAllSections :exec
DELETE FROM section`;

export async function deleteAllSections(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllSectionsQuery);
    await stmt.run();
}

export const deleteAllLessonsQuery = `-- name: DeleteAllLessons :exec
DELETE FROM lesson`;

export async function deleteAllLessons(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllLessonsQuery);
    await stmt.run();
}

export const getLessonCountQuery = `-- name: GetLessonCount :one
SELECT COUNT(*) AS lesson_count FROM lesson`;

export interface GetLessonCountRow {
    lessonCount: number;
}

export async function getLessonCount(database: Database): Promise<GetLessonCountRow | null> {
    const stmt = database.prepare(getLessonCountQuery);
    const result = await stmt.get();
    if (result == undefined) {
        return null;
    }
    return result as GetLessonCountRow;
}

