// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getLessonHtmlQuery = `-- name: GetLessonHtml :one
SELECT lesson.html FROM lesson WHERE lesson.id = ?`;

export interface GetLessonHtmlArgs {
    id: any;
}

export interface GetLessonHtmlRow {
    html: any;
}

export async function getLessonHtml(database: Database, args: GetLessonHtmlArgs): Promise<GetLessonHtmlRow | null> {
    const stmt = database.prepare(getLessonHtmlQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetLessonHtmlRow;
}

export const updateLessonHtmlQuery = `-- name: UpdateLessonHtml :exec
UPDATE lesson SET html = ? WHERE lesson.id = ?`;

export interface UpdateLessonHtmlArgs {
    html: any;
    id: any;
}

export async function updateLessonHtml(database: Database, args: UpdateLessonHtmlArgs): Promise<void> {
    const stmt = database.prepare(updateLessonHtmlQuery);
    await stmt.run(args.html, args.id);
}

