// Code generated by sqlc-gen-ts-d1. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
//   sqlc-gen-ts-d1 v0.0.0-a@dfd4bfef4736967ca17cc23d18de20920fbd196998fe7aa191a205439d63fb58

export type Course = {
  id: number;
  slug: string;
  title: string;
};

export type Category = {
  id: number;
  slug: string;
  title: string;
  courseId: number;
};

export type Section = {
  id: number;
  slug: string;
  title: string;
  courseId: number;
  categoryId: number;
};

export type Lesson = {
  id: number;
  slug: string;
  title: string;
  html: string;
  lessonOrder: number;
  courseId: number;
  categoryId: number;
  sectionId: number;
  keywords: string;
};

export type Users = {
  id: number;
  username: string;
  userPassword: string;
  displayName: string | null;
  lastVisitedAt: string;
};

export type Progress = {
  lessonId: number;
  userId: number;
  readAt: string;
};

export type SchemaVersion = {
  version: number;
  description: string;
  appliedAt: string;
};

