// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getTotalXpQuery = `-- name: GetTotalXp :one
SELECT COALESCE(SUM(lesson."order"), 0) AS totalorder FROM progress INNER JOIN lesson ON progress.lesson_id = lesson.id WHERE progress.user_id = ?`;

export interface GetTotalXpArgs {
    userId: any;
}

export interface GetTotalXpRow {
    totalorder: any | null;
}

export async function getTotalXp(database: Database, args: GetTotalXpArgs): Promise<GetTotalXpRow | null> {
    const stmt = database.prepare(getTotalXpQuery);
    const result = await stmt.get(args.userId);
    if (result == undefined) {
        return null;
    }
    return result as GetTotalXpRow;
}

export const getReadLessonsBySectionQuery = `-- name: GetReadLessonsBySection :many
SELECT lesson.slug FROM progress INNER JOIN lesson ON progress.lesson_id = lesson.id WHERE progress.user_id = ? AND lesson.section_id = ?`;

export interface GetReadLessonsBySectionArgs {
    userId: any;
    sectionId: any;
}

export interface GetReadLessonsBySectionRow {
    slug: any;
}

export async function getReadLessonsBySection(database: Database, args: GetReadLessonsBySectionArgs): Promise<GetReadLessonsBySectionRow[]> {
    const stmt = database.prepare(getReadLessonsBySectionQuery);
    const result = await stmt.all(args.userId, args.sectionId);
    return result as GetReadLessonsBySectionRow[];
}

export const isLessonReadQuery = `-- name: IsLessonRead :one
SELECT COUNT(*) AS readcount FROM progress WHERE progress.lesson_id = ? AND progress.user_id = ?`;

export interface IsLessonReadArgs {
    lessonId: any;
    userId: any;
}

export interface IsLessonReadRow {
    readcount: number;
}

export async function isLessonRead(database: Database, args: IsLessonReadArgs): Promise<IsLessonReadRow | null> {
    const stmt = database.prepare(isLessonReadQuery);
    const result = await stmt.get(args.lessonId, args.userId);
    if (result == undefined) {
        return null;
    }
    return result as IsLessonReadRow;
}

export const markLessonReadQuery = `-- name: MarkLessonRead :exec
INSERT OR IGNORE INTO progress (lesson_id, user_id, read_at) VALUES (?, ?, datetime('now'))`;

export interface MarkLessonReadArgs {
    lessonId: any;
    userId: any;
}

export async function markLessonRead(database: Database, args: MarkLessonReadArgs): Promise<void> {
    const stmt = database.prepare(markLessonReadQuery);
    await stmt.run(args.lessonId, args.userId);
}

export const resetSectionProgressQuery = `-- name: ResetSectionProgress :exec
DELETE FROM progress WHERE progress.user_id = ? AND progress.lesson_id IN (SELECT lesson.id FROM lesson WHERE lesson.section_id = ?)`;

export interface ResetSectionProgressArgs {
    userId: any;
    sectionId: any;
}

export async function resetSectionProgress(database: Database, args: ResetSectionProgressArgs): Promise<void> {
    const stmt = database.prepare(resetSectionProgressQuery);
    await stmt.run(args.userId, args.sectionId);
}

export const getReadCountsByCourseQuery = `-- name: GetReadCountsByCourse :many
SELECT lesson.section_id AS sectionid, COUNT(*) AS readcount FROM progress INNER JOIN lesson ON progress.lesson_id = lesson.id WHERE progress.user_id = ? AND lesson.course_id = ? GROUP BY lesson.section_id`;

export interface GetReadCountsByCourseArgs {
    userId: any;
    courseId: any;
}

export interface GetReadCountsByCourseRow {
    sectionid: any;
    readcount: number;
}

export async function getReadCountsByCourse(database: Database, args: GetReadCountsByCourseArgs): Promise<GetReadCountsByCourseRow[]> {
    const stmt = database.prepare(getReadCountsByCourseQuery);
    const result = await stmt.all(args.userId, args.courseId);
    return result as GetReadCountsByCourseRow[];
}

export const deleteAllProgressQuery = `-- name: DeleteAllProgress :exec
DELETE FROM progress`;

export async function deleteAllProgress(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllProgressQuery);
    await stmt.run();
}

export const getAllReadLessonsQuery = `-- name: GetAllReadLessons :many
SELECT progress.lesson_id AS lessonid FROM progress WHERE progress.user_id = ?`;

export interface GetAllReadLessonsArgs {
    userId: any;
}

export interface GetAllReadLessonsRow {
    lessonid: any;
}

export async function getAllReadLessons(database: Database, args: GetAllReadLessonsArgs): Promise<GetAllReadLessonsRow[]> {
    const stmt = database.prepare(getAllReadLessonsQuery);
    const result = await stmt.all(args.userId);
    return result as GetAllReadLessonsRow[];
}

