// Code generated by sqlc-gen-ts-d1. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
//   sqlc-gen-ts-d1 v0.0.0-a@dfd4bfef4736967ca17cc23d18de20920fbd196998fe7aa191a205439d63fb58


type Query<T> = {
  then(onFulfilled?: (value: T) => void, onRejected?: (reason?: any) => void): void;
  batch(): D1PreparedStatement;
}
const ensureCourseTableQuery = `-- name: EnsureCourseTable :exec
CREATE TABLE IF NOT EXISTS course (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL
)`;

export function ensureCourseTable(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(ensureCourseTableQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const ensureCategoryTableQuery = `-- name: EnsureCategoryTable :exec
CREATE TABLE IF NOT EXISTS category (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  course_id INTEGER NOT NULL REFERENCES course(id),
  UNIQUE(course_id, slug)
)`;

export function ensureCategoryTable(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(ensureCategoryTableQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const ensureSectionTableQuery = `-- name: EnsureSectionTable :exec
CREATE TABLE IF NOT EXISTS section (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  course_id INTEGER NOT NULL REFERENCES course(id),
  category_id INTEGER NOT NULL REFERENCES category(id),
  UNIQUE(course_id, category_id, slug)
)`;

export function ensureSectionTable(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(ensureSectionTableQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const ensureLessonTableQuery = `-- name: EnsureLessonTable :exec
CREATE TABLE IF NOT EXISTS lesson (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  html TEXT NOT NULL DEFAULT '',
  lesson_highlights TEXT NOT NULL DEFAULT '',
  lesson_order INTEGER NOT NULL DEFAULT 0,
  course_id INTEGER NOT NULL REFERENCES course(id),
  category_id INTEGER NOT NULL REFERENCES category(id),
  section_id INTEGER NOT NULL REFERENCES section(id),
  keywords TEXT NOT NULL DEFAULT '[]',
  UNIQUE(course_id, category_id, section_id, slug)
)`;

export function ensureLessonTable(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(ensureLessonTableQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const ensureUsersTableQuery = `-- name: EnsureUsersTable :exec
CREATE TABLE IF NOT EXISTS users (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL UNIQUE,
  user_password TEXT NOT NULL,
  display_name TEXT,
  last_visited_at TEXT NOT NULL DEFAULT (datetime('now'))
)`;

export function ensureUsersTable(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(ensureUsersTableQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const ensureProgressTableQuery = `-- name: EnsureProgressTable :exec
CREATE TABLE IF NOT EXISTS progress (
  lesson_id INTEGER NOT NULL REFERENCES lesson(id),
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  read_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (lesson_id, user_id)
)`;

export function ensureProgressTable(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(ensureProgressTableQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCategoriesByCourseQuery = `-- name: GetCategoriesByCourse :many
SELECT category.id, category.slug, category.title FROM category WHERE category.course_id = ?`;

export type GetCategoriesByCourseParams = {
  courseId: number;
};

export type GetCategoriesByCourseRow = {
  id: number;
  slug: string;
  title: string;
};

export function getCategoriesByCourse(
  d1: D1Database,
  args: GetCategoriesByCourseParams
): Query<D1Result<GetCategoriesByCourseRow>> {
  const ps = d1
    .prepare(getCategoriesByCourseQuery)
    .bind(args.courseId);
  return {
    then(onFulfilled?: (value: D1Result<GetCategoriesByCourseRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetCategoriesByCourseRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCategoryLessonCountsQuery = `-- name: GetCategoryLessonCounts :many
SELECT category.slug AS categoryslug, COUNT(lesson.id) AS lessoncount
FROM category
INNER JOIN lesson ON lesson.category_id = category.id
WHERE category.course_id = ?
GROUP BY category.id`;

export type GetCategoryLessonCountsParams = {
  courseId: number;
};

export type GetCategoryLessonCountsRow = {
  categoryslug: string;
  lessoncount: number;
};

export function getCategoryLessonCounts(
  d1: D1Database,
  args: GetCategoryLessonCountsParams
): Query<D1Result<GetCategoryLessonCountsRow>> {
  const ps = d1
    .prepare(getCategoryLessonCountsQuery)
    .bind(args.courseId);
  return {
    then(onFulfilled?: (value: D1Result<GetCategoryLessonCountsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetCategoryLessonCountsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getAllCategoriesQuery = `-- name: GetAllCategories :many
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category`;

export type GetAllCategoriesRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
};

export function getAllCategories(
  d1: D1Database
): Query<D1Result<GetAllCategoriesRow>> {
  const ps = d1
    .prepare(getAllCategoriesQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetAllCategoriesRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetAllCategoriesRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCategoryByIdQuery = `-- name: GetCategoryById :one
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category WHERE category.id = ?`;

export type GetCategoryByIdParams = {
  id: number;
};

export type GetCategoryByIdRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
};

export function getCategoryById(
  d1: D1Database,
  args: GetCategoryByIdParams
): Query<GetCategoryByIdRow | null> {
  const ps = d1
    .prepare(getCategoryByIdQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: GetCategoryByIdRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetCategoryByIdRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCategoryBySlugQuery = `-- name: GetCategoryBySlug :one
SELECT category.id, category.slug, category.title, category.course_id AS courseid FROM category WHERE category.slug = ? AND category.course_id = ?`;

export type GetCategoryBySlugParams = {
  slug: string;
  courseId: number;
};

export type GetCategoryBySlugRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
};

export function getCategoryBySlug(
  d1: D1Database,
  args: GetCategoryBySlugParams
): Query<GetCategoryBySlugRow | null> {
  const ps = d1
    .prepare(getCategoryBySlugQuery)
    .bind(args.slug, args.courseId);
  return {
    then(onFulfilled?: (value: GetCategoryBySlugRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetCategoryBySlugRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const createCategoryQuery = `-- name: CreateCategory :one
INSERT INTO category (slug, title, course_id) VALUES (?, ?, ?) RETURNING id`;

export type CreateCategoryParams = {
  slug: string;
  title: string;
  courseId: number;
};

export type CreateCategoryRow = {
  id: number;
};

export function createCategory(
  d1: D1Database,
  args: CreateCategoryParams
): Query<CreateCategoryRow | null> {
  const ps = d1
    .prepare(createCategoryQuery)
    .bind(args.slug, args.title, args.courseId);
  return {
    then(onFulfilled?: (value: CreateCategoryRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<CreateCategoryRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteAllCategoriesQuery = `-- name: DeleteAllCategories :exec
DELETE FROM category`;

export function deleteAllCategories(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(deleteAllCategoriesQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCourseByIdQuery = `-- name: GetCourseById :one
SELECT course.id, course.slug, course.title FROM course WHERE course.id = ?`;

export type GetCourseByIdParams = {
  id: number;
};

export type GetCourseByIdRow = {
  id: number;
  slug: string;
  title: string;
};

export function getCourseById(
  d1: D1Database,
  args: GetCourseByIdParams
): Query<GetCourseByIdRow | null> {
  const ps = d1
    .prepare(getCourseByIdQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: GetCourseByIdRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetCourseByIdRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCourseBySlugQuery = `-- name: GetCourseBySlug :one
SELECT course.id, course.slug, course.title FROM course WHERE course.slug = ?`;

export type GetCourseBySlugParams = {
  slug: string;
};

export type GetCourseBySlugRow = {
  id: number;
  slug: string;
  title: string;
};

export function getCourseBySlug(
  d1: D1Database,
  args: GetCourseBySlugParams
): Query<GetCourseBySlugRow | null> {
  const ps = d1
    .prepare(getCourseBySlugQuery)
    .bind(args.slug);
  return {
    then(onFulfilled?: (value: GetCourseBySlugRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetCourseBySlugRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getAllCoursesQuery = `-- name: GetAllCourses :many
SELECT course.id, course.slug, course.title FROM course`;

export type GetAllCoursesRow = {
  id: number;
  slug: string;
  title: string;
};

export function getAllCourses(
  d1: D1Database
): Query<D1Result<GetAllCoursesRow>> {
  const ps = d1
    .prepare(getAllCoursesQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetAllCoursesRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetAllCoursesRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const createCourseQuery = `-- name: CreateCourse :one
INSERT INTO course (slug, title) VALUES (?, ?) RETURNING id`;

export type CreateCourseParams = {
  slug: string;
  title: string;
};

export type CreateCourseRow = {
  id: number;
};

export function createCourse(
  d1: D1Database,
  args: CreateCourseParams
): Query<CreateCourseRow | null> {
  const ps = d1
    .prepare(createCourseQuery)
    .bind(args.slug, args.title);
  return {
    then(onFulfilled?: (value: CreateCourseRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<CreateCourseRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteAllCoursesQuery = `-- name: DeleteAllCourses :exec
DELETE FROM course`;

export function deleteAllCourses(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(deleteAllCoursesQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getBreadcrumbsQuery = `-- name: GetBreadcrumbs :one
SELECT course.title AS coursetitle,
       category.title AS categorytitle,
       section.title AS sectiontitle
FROM course
LEFT JOIN category ON category.course_id = course.id AND category.slug = ?1
LEFT JOIN section ON section.category_id = category.id AND section.slug = ?2
WHERE course.slug = ?3`;

export type GetBreadcrumbsParams = {
  categoryslug: string;
  sectionslug: string;
  courseslug: string;
};

export type GetBreadcrumbsRow = {
  coursetitle: string;
  categorytitle: string | null;
  sectiontitle: string | null;
};

export function getBreadcrumbs(
  d1: D1Database,
  args: GetBreadcrumbsParams
): Query<GetBreadcrumbsRow | null> {
  const ps = d1
    .prepare(getBreadcrumbsQuery)
    .bind(args.categoryslug, args.sectionslug, args.courseslug);
  return {
    then(onFulfilled?: (value: GetBreadcrumbsRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetBreadcrumbsRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonsBySectionQuery = `-- name: GetLessonsBySection :many
SELECT lesson.id, lesson.slug, lesson.title, lesson.lesson_order AS lessonorder FROM lesson WHERE lesson.section_id = ? ORDER BY lesson.lesson_order`;

export type GetLessonsBySectionParams = {
  sectionId: number;
};

export type GetLessonsBySectionRow = {
  id: number;
  slug: string;
  title: string;
  lessonorder: number;
};

export function getLessonsBySection(
  d1: D1Database,
  args: GetLessonsBySectionParams
): Query<D1Result<GetLessonsBySectionRow>> {
  const ps = d1
    .prepare(getLessonsBySectionQuery)
    .bind(args.sectionId);
  return {
    then(onFulfilled?: (value: D1Result<GetLessonsBySectionRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetLessonsBySectionRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonByIdQuery = `-- name: GetLessonById :one
SELECT lesson.id, lesson.slug, lesson.title, lesson.lesson_order AS lessonorder, lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson WHERE lesson.id = ?`;

export type GetLessonByIdParams = {
  id: number;
};

export type GetLessonByIdRow = {
  id: number;
  slug: string;
  title: string;
  lessonorder: number;
  sectionid: number;
  categoryid: number;
  courseid: number;
};

export function getLessonById(
  d1: D1Database,
  args: GetLessonByIdParams
): Query<GetLessonByIdRow | null> {
  const ps = d1
    .prepare(getLessonByIdQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: GetLessonByIdRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetLessonByIdRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonBySlugQuery = `-- name: GetLessonBySlug :one
SELECT lesson.id, lesson.slug, lesson.title, lesson.lesson_order AS lessonorder, lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson WHERE lesson.slug = ? AND lesson.section_id = ?`;

export type GetLessonBySlugParams = {
  slug: string;
  sectionId: number;
};

export type GetLessonBySlugRow = {
  id: number;
  slug: string;
  title: string;
  lessonorder: number;
  sectionid: number;
  categoryid: number;
  courseid: number;
};

export function getLessonBySlug(
  d1: D1Database,
  args: GetLessonBySlugParams
): Query<GetLessonBySlugRow | null> {
  const ps = d1
    .prepare(getLessonBySlugQuery)
    .bind(args.slug, args.sectionId);
  return {
    then(onFulfilled?: (value: GetLessonBySlugRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetLessonBySlugRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getAllLessonsQuery = `-- name: GetAllLessons :many
SELECT lesson.id, lesson.slug, lesson.title, lesson.lesson_order AS lessonorder, lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson`;

export type GetAllLessonsRow = {
  id: number;
  slug: string;
  title: string;
  lessonorder: number;
  sectionid: number;
  categoryid: number;
  courseid: number;
};

export function getAllLessons(
  d1: D1Database
): Query<D1Result<GetAllLessonsRow>> {
  const ps = d1
    .prepare(getAllLessonsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetAllLessonsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetAllLessonsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const createLessonQuery = `-- name: CreateLesson :one
INSERT INTO lesson (slug, title, html, lesson_highlights, lesson_order, course_id, category_id, section_id, keywords) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id`;

export type CreateLessonParams = {
  slug: string;
  title: string;
  html: string;
  lessonHighlights: string;
  lessonOrder: number;
  courseId: number;
  categoryId: number;
  sectionId: number;
  keywords: string;
};

export type CreateLessonRow = {
  id: number;
};

export function createLesson(
  d1: D1Database,
  args: CreateLessonParams
): Query<CreateLessonRow | null> {
  const ps = d1
    .prepare(createLessonQuery)
    .bind(args.slug, args.title, args.html, args.lessonHighlights, args.lessonOrder, args.courseId, args.categoryId, args.sectionId, args.keywords);
  return {
    then(onFulfilled?: (value: CreateLessonRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<CreateLessonRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteAllLessonsQuery = `-- name: DeleteAllLessons :exec
DELETE FROM lesson`;

export function deleteAllLessons(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(deleteAllLessonsQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonCountQuery = `-- name: GetLessonCount :one
SELECT COUNT(*) AS lessoncount FROM lesson`;

export type GetLessonCountRow = {
  lessoncount: number;
};

export function getLessonCount(
  d1: D1Database
): Query<GetLessonCountRow | null> {
  const ps = d1
    .prepare(getLessonCountQuery);
  return {
    then(onFulfilled?: (value: GetLessonCountRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetLessonCountRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonHtmlQuery = `-- name: GetLessonHtml :one
SELECT lesson.html FROM lesson WHERE lesson.id = ?`;

export type GetLessonHtmlParams = {
  id: number;
};

export type GetLessonHtmlRow = {
  html: string;
};

export function getLessonHtml(
  d1: D1Database,
  args: GetLessonHtmlParams
): Query<GetLessonHtmlRow | null> {
  const ps = d1
    .prepare(getLessonHtmlQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: GetLessonHtmlRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetLessonHtmlRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const updateLessonHtmlQuery = `-- name: UpdateLessonHtml :exec
UPDATE lesson SET html = ? WHERE lesson.id = ?`;

export type UpdateLessonHtmlParams = {
  html: string;
  id: number;
};

export function updateLessonHtml(
  d1: D1Database,
  args: UpdateLessonHtmlParams
): Query<D1Result> {
  const ps = d1
    .prepare(updateLessonHtmlQuery)
    .bind(args.html, args.id);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSearchLessonsQuery = `-- name: GetSearchLessons :many
SELECT lesson.slug, lesson.title, lesson.html, lesson.keywords, lesson.section_id AS sectionid, lesson.category_id AS categoryid, lesson.course_id AS courseid FROM lesson WHERE lesson.html != ''`;

export type GetSearchLessonsRow = {
  slug: string;
  title: string;
  html: string;
  keywords: string;
  sectionid: number;
  categoryid: number;
  courseid: number;
};

export function getSearchLessons(
  d1: D1Database
): Query<D1Result<GetSearchLessonsRow>> {
  const ps = d1
    .prepare(getSearchLessonsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetSearchLessonsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetSearchLessonsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonsByCategoryGroupedQuery = `-- name: GetLessonsByCategoryGrouped :many
SELECT lesson.id, lesson.slug, lesson.title, lesson.lesson_order AS lessonorder,
       lesson.section_id AS sectionid, section.slug AS secslug,
       section.title AS sectitle
FROM lesson
INNER JOIN section ON lesson.section_id = section.id
WHERE lesson.category_id = ?
ORDER BY section.id, lesson.lesson_order`;

export type GetLessonsByCategoryGroupedParams = {
  categoryId: number;
};

export type GetLessonsByCategoryGroupedRow = {
  id: number;
  slug: string;
  title: string;
  lessonorder: number;
  sectionid: number;
  secslug: string;
  sectitle: string;
};

export function getLessonsByCategoryGrouped(
  d1: D1Database,
  args: GetLessonsByCategoryGroupedParams
): Query<D1Result<GetLessonsByCategoryGroupedRow>> {
  const ps = d1
    .prepare(getLessonsByCategoryGroupedQuery)
    .bind(args.categoryId);
  return {
    then(onFulfilled?: (value: D1Result<GetLessonsByCategoryGroupedRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetLessonsByCategoryGroupedRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getReadLessonsBySectionQuery = `-- name: GetReadLessonsBySection :many
SELECT lesson.slug FROM progress INNER JOIN lesson ON progress.lesson_id = lesson.id WHERE progress.user_id = ? AND lesson.section_id = ?`;

export type GetReadLessonsBySectionParams = {
  userId: number;
  sectionId: number;
};

export type GetReadLessonsBySectionRow = {
  slug: string;
};

export function getReadLessonsBySection(
  d1: D1Database,
  args: GetReadLessonsBySectionParams
): Query<D1Result<GetReadLessonsBySectionRow>> {
  const ps = d1
    .prepare(getReadLessonsBySectionQuery)
    .bind(args.userId, args.sectionId);
  return {
    then(onFulfilled?: (value: D1Result<GetReadLessonsBySectionRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetReadLessonsBySectionRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getAllReadLessonsQuery = `-- name: GetAllReadLessons :many
SELECT progress.lesson_id AS lessonid, lesson.lesson_order AS lessonorder FROM progress INNER JOIN lesson ON progress.lesson_id = lesson.id WHERE progress.user_id = ?`;

export type GetAllReadLessonsParams = {
  userId: number;
};

export type GetAllReadLessonsRow = {
  lessonid: number;
  lessonorder: number;
};

export function getAllReadLessons(
  d1: D1Database,
  args: GetAllReadLessonsParams
): Query<D1Result<GetAllReadLessonsRow>> {
  const ps = d1
    .prepare(getAllReadLessonsQuery)
    .bind(args.userId);
  return {
    then(onFulfilled?: (value: D1Result<GetAllReadLessonsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetAllReadLessonsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const isLessonReadQuery = `-- name: IsLessonRead :one
SELECT COUNT(*) > 0 AS isread FROM progress WHERE progress.lesson_id = ? AND progress.user_id = ?`;

export type IsLessonReadParams = {
  lessonId: number;
  userId: number;
};

export type IsLessonReadRow = {
  isread: number | string;
};

export function isLessonRead(
  d1: D1Database,
  args: IsLessonReadParams
): Query<IsLessonReadRow | null> {
  const ps = d1
    .prepare(isLessonReadQuery)
    .bind(args.lessonId, args.userId);
  return {
    then(onFulfilled?: (value: IsLessonReadRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<IsLessonReadRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const markLessonReadQuery = `-- name: MarkLessonRead :exec
INSERT OR IGNORE INTO progress (lesson_id, user_id, read_at) VALUES (?, ?, datetime('now'))`;

export type MarkLessonReadParams = {
  lessonId: number;
  userId: number;
};

export function markLessonRead(
  d1: D1Database,
  args: MarkLessonReadParams
): Query<D1Result> {
  const ps = d1
    .prepare(markLessonReadQuery)
    .bind(args.lessonId, args.userId);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const resetSectionProgressQuery = `-- name: ResetSectionProgress :exec
DELETE FROM progress WHERE progress.user_id = ? AND progress.lesson_id IN (SELECT lesson.id FROM lesson WHERE lesson.section_id = ?)`;

export type ResetSectionProgressParams = {
  userId: number;
  sectionId: number;
};

export function resetSectionProgress(
  d1: D1Database,
  args: ResetSectionProgressParams
): Query<D1Result> {
  const ps = d1
    .prepare(resetSectionProgressQuery)
    .bind(args.userId, args.sectionId);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getReadCountsByCourseQuery = `-- name: GetReadCountsByCourse :many
SELECT lesson.section_id AS sectionid, COUNT(*) AS readcount FROM progress INNER JOIN lesson ON progress.lesson_id = lesson.id WHERE progress.user_id = ? AND lesson.course_id = ? GROUP BY lesson.section_id`;

export type GetReadCountsByCourseParams = {
  userId: number;
  courseId: number;
};

export type GetReadCountsByCourseRow = {
  sectionid: number;
  readcount: number;
};

export function getReadCountsByCourse(
  d1: D1Database,
  args: GetReadCountsByCourseParams
): Query<D1Result<GetReadCountsByCourseRow>> {
  const ps = d1
    .prepare(getReadCountsByCourseQuery)
    .bind(args.userId, args.courseId);
  return {
    then(onFulfilled?: (value: D1Result<GetReadCountsByCourseRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetReadCountsByCourseRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteAllProgressQuery = `-- name: DeleteAllProgress :exec
DELETE FROM progress`;

export function deleteAllProgress(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(deleteAllProgressQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const resetUserProgressQuery = `-- name: ResetUserProgress :exec
DELETE FROM progress WHERE user_id = ?`;

export type ResetUserProgressParams = {
  userId: number;
};

export function resetUserProgress(
  d1: D1Database,
  args: ResetUserProgressParams
): Query<D1Result> {
  const ps = d1
    .prepare(resetUserProgressQuery)
    .bind(args.userId);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionsByCategoryQuery = `-- name: GetSectionsByCategory :many
SELECT section.id, section.slug, section.title FROM section WHERE section.category_id = ?`;

export type GetSectionsByCategoryParams = {
  categoryId: number;
};

export type GetSectionsByCategoryRow = {
  id: number;
  slug: string;
  title: string;
};

export function getSectionsByCategory(
  d1: D1Database,
  args: GetSectionsByCategoryParams
): Query<D1Result<GetSectionsByCategoryRow>> {
  const ps = d1
    .prepare(getSectionsByCategoryQuery)
    .bind(args.categoryId);
  return {
    then(onFulfilled?: (value: D1Result<GetSectionsByCategoryRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetSectionsByCategoryRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getAllSectionsQuery = `-- name: GetAllSections :many
SELECT section.id, section.slug, section.title, section.category_id AS categoryid, section.course_id AS courseid FROM section`;

export type GetAllSectionsRow = {
  id: number;
  slug: string;
  title: string;
  categoryid: number;
  courseid: number;
};

export function getAllSections(
  d1: D1Database
): Query<D1Result<GetAllSectionsRow>> {
  const ps = d1
    .prepare(getAllSectionsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetAllSectionsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetAllSectionsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionByIdQuery = `-- name: GetSectionById :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid FROM section WHERE section.id = ?`;

export type GetSectionByIdParams = {
  id: number;
};

export type GetSectionByIdRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
  categoryid: number;
};

export function getSectionById(
  d1: D1Database,
  args: GetSectionByIdParams
): Query<GetSectionByIdRow | null> {
  const ps = d1
    .prepare(getSectionByIdQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: GetSectionByIdRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetSectionByIdRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionBySlugQuery = `-- name: GetSectionBySlug :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid FROM section WHERE section.slug = ? AND section.category_id = ?`;

export type GetSectionBySlugParams = {
  slug: string;
  categoryId: number;
};

export type GetSectionBySlugRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
  categoryid: number;
};

export function getSectionBySlug(
  d1: D1Database,
  args: GetSectionBySlugParams
): Query<GetSectionBySlugRow | null> {
  const ps = d1
    .prepare(getSectionBySlugQuery)
    .bind(args.slug, args.categoryId);
  return {
    then(onFulfilled?: (value: GetSectionBySlugRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetSectionBySlugRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const createSectionQuery = `-- name: CreateSection :one
INSERT INTO section (slug, title, course_id, category_id) VALUES (?, ?, ?, ?) RETURNING id`;

export type CreateSectionParams = {
  slug: string;
  title: string;
  courseId: number;
  categoryId: number;
};

export type CreateSectionRow = {
  id: number;
};

export function createSection(
  d1: D1Database,
  args: CreateSectionParams
): Query<CreateSectionRow | null> {
  const ps = d1
    .prepare(createSectionQuery)
    .bind(args.slug, args.title, args.courseId, args.categoryId);
  return {
    then(onFulfilled?: (value: CreateSectionRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<CreateSectionRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteAllSectionsQuery = `-- name: DeleteAllSections :exec
DELETE FROM section`;

export function deleteAllSections(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(deleteAllSectionsQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionBySlugInCourseQuery = `-- name: GetSectionBySlugInCourse :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid
FROM section
INNER JOIN category ON section.category_id = category.id
WHERE category.course_id = ? AND section.slug = ?`;

export type GetSectionBySlugInCourseParams = {
  courseId: number;
  slug: string;
};

export type GetSectionBySlugInCourseRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
  categoryid: number;
};

export function getSectionBySlugInCourse(
  d1: D1Database,
  args: GetSectionBySlugInCourseParams
): Query<GetSectionBySlugInCourseRow | null> {
  const ps = d1
    .prepare(getSectionBySlugInCourseQuery)
    .bind(args.courseId, args.slug);
  return {
    then(onFulfilled?: (value: GetSectionBySlugInCourseRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetSectionBySlugInCourseRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionIdToSlugByCourseQuery = `-- name: GetSectionIdToSlugByCourse :many
SELECT section.id, section.slug
FROM section
INNER JOIN category ON section.category_id = category.id
WHERE category.course_id = ?`;

export type GetSectionIdToSlugByCourseParams = {
  courseId: number;
};

export type GetSectionIdToSlugByCourseRow = {
  id: number;
  slug: string;
};

export function getSectionIdToSlugByCourse(
  d1: D1Database,
  args: GetSectionIdToSlugByCourseParams
): Query<D1Result<GetSectionIdToSlugByCourseRow>> {
  const ps = d1
    .prepare(getSectionIdToSlugByCourseQuery)
    .bind(args.courseId);
  return {
    then(onFulfilled?: (value: D1Result<GetSectionIdToSlugByCourseRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetSectionIdToSlugByCourseRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCourseSectionLessonCountsQuery = `-- name: GetCourseSectionLessonCounts :many
SELECT category.slug AS categoryslug, section.slug AS sectionslug, COUNT(lesson.id) AS lessoncount
FROM section
INNER JOIN category ON section.category_id = category.id
LEFT JOIN lesson ON lesson.section_id = section.id
WHERE category.course_id = ?
GROUP BY category.id, section.id
ORDER BY category.id, section.id`;

export type GetCourseSectionLessonCountsParams = {
  courseId: number;
};

export type GetCourseSectionLessonCountsRow = {
  categoryslug: string;
  sectionslug: string;
  lessoncount: number;
};

export function getCourseSectionLessonCounts(
  d1: D1Database,
  args: GetCourseSectionLessonCountsParams
): Query<D1Result<GetCourseSectionLessonCountsRow>> {
  const ps = d1
    .prepare(getCourseSectionLessonCountsQuery)
    .bind(args.courseId);
  return {
    then(onFulfilled?: (value: D1Result<GetCourseSectionLessonCountsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetCourseSectionLessonCountsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionPageDataQuery = `-- name: GetSectionPageData :many
SELECT section.title AS sectitle,
       lesson.id, lesson.slug, lesson.title, lesson.lesson_order AS lessonorder
FROM section
INNER JOIN category ON section.category_id = category.id
INNER JOIN course ON category.course_id = course.id
INNER JOIN lesson ON lesson.section_id = section.id
WHERE course.slug = ?1
  AND category.slug = ?2
  AND section.slug = ?3
ORDER BY lesson.lesson_order`;

export type GetSectionPageDataParams = {
  courseslug: string;
  categoryslug: string;
  sectionslug: string;
};

export type GetSectionPageDataRow = {
  sectitle: string;
  id: number;
  slug: string;
  title: string;
  lessonorder: number;
};

export function getSectionPageData(
  d1: D1Database,
  args: GetSectionPageDataParams
): Query<D1Result<GetSectionPageDataRow>> {
  const ps = d1
    .prepare(getSectionPageDataQuery)
    .bind(args.courseslug, args.categoryslug, args.sectionslug);
  return {
    then(onFulfilled?: (value: D1Result<GetSectionPageDataRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetSectionPageDataRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCourseSyncRowsQuery = `-- name: GetCourseSyncRows :many
SELECT id, slug, title FROM course`;

export type GetCourseSyncRowsRow = {
  id: number;
  slug: string;
  title: string;
};

export function getCourseSyncRows(
  d1: D1Database
): Query<D1Result<GetCourseSyncRowsRow>> {
  const ps = d1
    .prepare(getCourseSyncRowsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetCourseSyncRowsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetCourseSyncRowsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getCategorySyncRowsQuery = `-- name: GetCategorySyncRows :many
SELECT id, slug, title, course_id AS courseid FROM category`;

export type GetCategorySyncRowsRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
};

export function getCategorySyncRows(
  d1: D1Database
): Query<D1Result<GetCategorySyncRowsRow>> {
  const ps = d1
    .prepare(getCategorySyncRowsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetCategorySyncRowsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetCategorySyncRowsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getSectionSyncRowsQuery = `-- name: GetSectionSyncRows :many
SELECT id, slug, title, course_id AS courseid, category_id AS categoryid FROM section`;

export type GetSectionSyncRowsRow = {
  id: number;
  slug: string;
  title: string;
  courseid: number;
  categoryid: number;
};

export function getSectionSyncRows(
  d1: D1Database
): Query<D1Result<GetSectionSyncRowsRow>> {
  const ps = d1
    .prepare(getSectionSyncRowsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetSectionSyncRowsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetSectionSyncRowsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonSyncRowsQuery = `-- name: GetLessonSyncRows :many
SELECT id, slug, title, html, lesson_order AS lessonorder, course_id AS courseid, category_id AS categoryid, section_id AS sectionid, keywords FROM lesson`;

export type GetLessonSyncRowsRow = {
  id: number;
  slug: string;
  title: string;
  html: string;
  lessonorder: number;
  courseid: number;
  categoryid: number;
  sectionid: number;
  keywords: string;
};

export function getLessonSyncRows(
  d1: D1Database
): Query<D1Result<GetLessonSyncRowsRow>> {
  const ps = d1
    .prepare(getLessonSyncRowsQuery);
  return {
    then(onFulfilled?: (value: D1Result<GetLessonSyncRowsRow>) => void, onRejected?: (reason?: any) => void) {
      ps.all<GetLessonSyncRowsRow>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const upsertCourseQuery = `-- name: UpsertCourse :exec
INSERT INTO course (id, slug, title) VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title`;

export type UpsertCourseParams = {
  id: number;
  slug: string;
  title: string;
};

export function upsertCourse(
  d1: D1Database,
  args: UpsertCourseParams
): Query<D1Result> {
  const ps = d1
    .prepare(upsertCourseQuery)
    .bind(args.id, args.slug, args.title);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const upsertCategoryQuery = `-- name: UpsertCategory :exec
INSERT INTO category (id, slug, title, course_id) VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, course_id = excluded.course_id`;

export type UpsertCategoryParams = {
  id: number;
  slug: string;
  title: string;
  courseId: number;
};

export function upsertCategory(
  d1: D1Database,
  args: UpsertCategoryParams
): Query<D1Result> {
  const ps = d1
    .prepare(upsertCategoryQuery)
    .bind(args.id, args.slug, args.title, args.courseId);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const upsertSectionQuery = `-- name: UpsertSection :exec
INSERT INTO section (id, slug, title, course_id, category_id) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, course_id = excluded.course_id, category_id = excluded.category_id`;

export type UpsertSectionParams = {
  id: number;
  slug: string;
  title: string;
  courseId: number;
  categoryId: number;
};

export function upsertSection(
  d1: D1Database,
  args: UpsertSectionParams
): Query<D1Result> {
  const ps = d1
    .prepare(upsertSectionQuery)
    .bind(args.id, args.slug, args.title, args.courseId, args.categoryId);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const upsertLessonQuery = `-- name: UpsertLesson :exec
INSERT INTO lesson (id, slug, title, html, lesson_order, course_id, category_id, section_id, keywords) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, html = excluded.html, lesson_order = excluded.lesson_order, course_id = excluded.course_id, category_id = excluded.category_id, section_id = excluded.section_id, keywords = excluded.keywords`;

export type UpsertLessonParams = {
  id: number;
  slug: string;
  title: string;
  html: string;
  lessonOrder: number;
  courseId: number;
  categoryId: number;
  sectionId: number;
  keywords: string;
};

export function upsertLesson(
  d1: D1Database,
  args: UpsertLessonParams
): Query<D1Result> {
  const ps = d1
    .prepare(upsertLessonQuery)
    .bind(args.id, args.slug, args.title, args.html, args.lessonOrder, args.courseId, args.categoryId, args.sectionId, args.keywords);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getLessonKeywordCountQuery = `-- name: GetLessonKeywordCount :one
SELECT COUNT(*) AS c FROM lesson WHERE keywords IS NOT NULL AND keywords != '[]'`;

export type GetLessonKeywordCountRow = {
  c: number;
};

export function getLessonKeywordCount(
  d1: D1Database
): Query<GetLessonKeywordCountRow | null> {
  const ps = d1
    .prepare(getLessonKeywordCountQuery);
  return {
    then(onFulfilled?: (value: GetLessonKeywordCountRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetLessonKeywordCountRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getUserByIdQuery = `-- name: GetUserById :one
SELECT users.id, users.username, users.display_name AS displayname FROM users WHERE users.id = ?`;

export type GetUserByIdParams = {
  id: number;
};

export type GetUserByIdRow = {
  id: number;
  username: string;
  displayname: string | null;
};

export function getUserById(
  d1: D1Database,
  args: GetUserByIdParams
): Query<GetUserByIdRow | null> {
  const ps = d1
    .prepare(getUserByIdQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: GetUserByIdRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetUserByIdRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getUserByUserNameQuery = `-- name: GetUserByUserName :one
SELECT users.id, users.username, users.display_name AS displayname FROM users WHERE users.username = ?`;

export type GetUserByUserNameParams = {
  username: string;
};

export type GetUserByUserNameRow = {
  id: number;
  username: string;
  displayname: string | null;
};

export function getUserByUserName(
  d1: D1Database,
  args: GetUserByUserNameParams
): Query<GetUserByUserNameRow | null> {
  const ps = d1
    .prepare(getUserByUserNameQuery)
    .bind(args.username);
  return {
    then(onFulfilled?: (value: GetUserByUserNameRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetUserByUserNameRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getUserByUserNameWithPasswordQuery = `-- name: GetUserByUserNameWithPassword :one
SELECT users.id, users.username, users.user_password AS userpassword, users.display_name AS displayname FROM users WHERE users.username = ?`;

export type GetUserByUserNameWithPasswordParams = {
  username: string;
};

export type GetUserByUserNameWithPasswordRow = {
  id: number;
  username: string;
  userpassword: string;
  displayname: string | null;
};

export function getUserByUserNameWithPassword(
  d1: D1Database,
  args: GetUserByUserNameWithPasswordParams
): Query<GetUserByUserNameWithPasswordRow | null> {
  const ps = d1
    .prepare(getUserByUserNameWithPasswordQuery)
    .bind(args.username);
  return {
    then(onFulfilled?: (value: GetUserByUserNameWithPasswordRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetUserByUserNameWithPasswordRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const upsertUserQuery = `-- name: UpsertUser :one
INSERT INTO users (username, user_password, display_name) VALUES (?,?,?) RETURNING id`;

export type UpsertUserParams = {
  username: string;
  userPassword: string;
  displayName: string | null;
};

export type UpsertUserRow = {
  id: number;
};

export function upsertUser(
  d1: D1Database,
  args: UpsertUserParams
): Query<UpsertUserRow | null> {
  const ps = d1
    .prepare(upsertUserQuery)
    .bind(args.username, args.userPassword, args.displayName);
  return {
    then(onFulfilled?: (value: UpsertUserRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<UpsertUserRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const updateDisplayNameQuery = `-- name: UpdateDisplayName :exec
UPDATE users SET display_name = ? WHERE id = ?`;

export type UpdateDisplayNameParams = {
  displayName: string | null;
  id: number;
};

export function updateDisplayName(
  d1: D1Database,
  args: UpdateDisplayNameParams
): Query<D1Result> {
  const ps = d1
    .prepare(updateDisplayNameQuery)
    .bind(args.displayName, args.id);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const updateLastVisitedAtQuery = `-- name: UpdateLastVisitedAt :exec
UPDATE users SET last_visited_at = datetime('now') WHERE id = ?`;

export type UpdateLastVisitedAtParams = {
  id: number;
};

export function updateLastVisitedAt(
  d1: D1Database,
  args: UpdateLastVisitedAtParams
): Query<D1Result> {
  const ps = d1
    .prepare(updateLastVisitedAtQuery)
    .bind(args.id);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteStaleUsersQuery = `-- name: DeleteStaleUsers :exec
DELETE FROM users WHERE last_visited_at < ?`;

export type DeleteStaleUsersParams = {
  lastVisitedAt: string;
};

export function deleteStaleUsers(
  d1: D1Database,
  args: DeleteStaleUsersParams
): Query<D1Result> {
  const ps = d1
    .prepare(deleteStaleUsersQuery)
    .bind(args.lastVisitedAt);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const getUserCountQuery = `-- name: GetUserCount :one
SELECT COUNT(*) AS count FROM users`;

export type GetUserCountRow = {
  count: number;
};

export function getUserCount(
  d1: D1Database
): Query<GetUserCountRow | null> {
  const ps = d1
    .prepare(getUserCountQuery);
  return {
    then(onFulfilled?: (value: GetUserCountRow | null) => void, onRejected?: (reason?: any) => void) {
      ps.first<GetUserCountRow | null>()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

const deleteAllUsersQuery = `-- name: DeleteAllUsers :exec
DELETE FROM users`;

export function deleteAllUsers(
  d1: D1Database
): Query<D1Result> {
  const ps = d1
    .prepare(deleteAllUsersQuery);
  return {
    then(onFulfilled?: (value: D1Result) => void, onRejected?: (reason?: any) => void) {
      ps.run()
        .then(onFulfilled).catch(onRejected);
    },
    batch() { return ps; },
  }
}

