// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const ensureCourseTableQuery = `-- name: EnsureCourseTable :exec
CREATE TABLE IF NOT EXISTS course (
  course_id TEXT NOT NULL PRIMARY KEY,
  slug TEXT NOT NULL,
  title TEXT NOT NULL
)`;

export async function ensureCourseTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureCourseTableQuery);
    await stmt.run();
}

export const ensureCategoryTableQuery = `-- name: EnsureCategoryTable :exec
CREATE TABLE IF NOT EXISTS category (
  category_id TEXT NOT NULL PRIMARY KEY,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  course_id TEXT NOT NULL REFERENCES course(course_id)
)`;

export async function ensureCategoryTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureCategoryTableQuery);
    await stmt.run();
}

export const ensureSectionTableQuery = `-- name: EnsureSectionTable :exec
CREATE TABLE IF NOT EXISTS section (
  section_id TEXT NOT NULL PRIMARY KEY,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  course_id TEXT NOT NULL REFERENCES course(course_id),
  category_id TEXT NOT NULL REFERENCES category(category_id)
)`;

export async function ensureSectionTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureSectionTableQuery);
    await stmt.run();
}

export const ensureLessonTableQuery = `-- name: EnsureLessonTable :exec
CREATE TABLE IF NOT EXISTS lesson (
  lesson_id TEXT NOT NULL PRIMARY KEY,
  slug TEXT NOT NULL,
  title TEXT NOT NULL,
  html TEXT NOT NULL DEFAULT '',
  "order" INTEGER NOT NULL,
  course_id TEXT NOT NULL REFERENCES course(course_id),
  category_id TEXT NOT NULL REFERENCES category(category_id),
  section_id TEXT NOT NULL REFERENCES section(section_id)
)`;

export async function ensureLessonTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureLessonTableQuery);
    await stmt.run();
}

export const ensureUserTableQuery = `-- name: EnsureUserTable :exec
CREATE TABLE IF NOT EXISTS "user" (
  user_id TEXT NOT NULL PRIMARY KEY,
  name TEXT NOT NULL
)`;

export async function ensureUserTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureUserTableQuery);
    await stmt.run();
}

export const ensureProgressTableQuery = `-- name: EnsureProgressTable :exec
CREATE TABLE IF NOT EXISTS progress (
  lesson_id TEXT NOT NULL REFERENCES lesson(lesson_id),
  user_id TEXT NOT NULL REFERENCES "user"(user_id),
  read_at TEXT NOT NULL DEFAULT (datetime('now')),
  PRIMARY KEY (lesson_id, user_id)
)`;

export async function ensureProgressTable(database: Database): Promise<void> {
    const stmt = database.prepare(ensureProgressTableQuery);
    await stmt.run();
}

