// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getSectionsByCategoryQuery = `-- name: GetSectionsByCategory :many
SELECT section.id, section.slug, section.title FROM section WHERE section.category_id = ?`;

export interface GetSectionsByCategoryArgs {
    categoryId: any;
}

export interface GetSectionsByCategoryRow {
    id: any;
    slug: any;
    title: any;
}

export async function getSectionsByCategory(database: Database, args: GetSectionsByCategoryArgs): Promise<GetSectionsByCategoryRow[]> {
    const stmt = database.prepare(getSectionsByCategoryQuery);
    const result = await stmt.all(args.categoryId);
    return result as GetSectionsByCategoryRow[];
}

export const getAllSectionsQuery = `-- name: GetAllSections :many
SELECT section.id, section.slug, section.title, section.category_id AS categoryid, section.course_id AS courseid FROM section`;

export interface GetAllSectionsRow {
    id: any;
    slug: any;
    title: any;
    categoryid: any;
    courseid: any;
}

export async function getAllSections(database: Database): Promise<GetAllSectionsRow[]> {
    const stmt = database.prepare(getAllSectionsQuery);
    const result = await stmt.all();
    return result as GetAllSectionsRow[];
}

export const getSectionByIdQuery = `-- name: GetSectionById :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid FROM section WHERE section.id = ?`;

export interface GetSectionByIdArgs {
    id: any;
}

export interface GetSectionByIdRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
    categoryid: any;
}

export async function getSectionById(database: Database, args: GetSectionByIdArgs): Promise<GetSectionByIdRow | null> {
    const stmt = database.prepare(getSectionByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetSectionByIdRow;
}

export const getSectionBySlugQuery = `-- name: GetSectionBySlug :one
SELECT section.id, section.slug, section.title, section.course_id AS courseid, section.category_id AS categoryid FROM section WHERE section.slug = ? AND section.category_id = ?`;

export interface GetSectionBySlugArgs {
    slug: any;
    categoryId: any;
}

export interface GetSectionBySlugRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
    categoryid: any;
}

export async function getSectionBySlug(database: Database, args: GetSectionBySlugArgs): Promise<GetSectionBySlugRow | null> {
    const stmt = database.prepare(getSectionBySlugQuery);
    const result = await stmt.get(args.slug, args.categoryId);
    if (result == undefined) {
        return null;
    }
    return result as GetSectionBySlugRow;
}

export const createSectionQuery = `-- name: CreateSection :one
INSERT INTO section (slug, title, course_id, category_id) VALUES (?, ?, ?, ?) RETURNING id`;

export interface CreateSectionArgs {
    slug: any;
    title: any;
    courseId: any;
    categoryId: any;
}

export interface CreateSectionRow {
    id: any;
}

export async function createSection(database: Database, args: CreateSectionArgs): Promise<CreateSectionRow | null> {
    const stmt = database.prepare(createSectionQuery);
    const result = await stmt.get(args.slug, args.title, args.courseId, args.categoryId);
    if (result == undefined) {
        return null;
    }
    return result as CreateSectionRow;
}

export const deleteAllSectionsQuery = `-- name: DeleteAllSections :exec
DELETE FROM section`;

export async function deleteAllSections(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllSectionsQuery);
    await stmt.run();
}

