// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getUserByIdQuery = `-- name: GetUserById :one
SELECT users.id, users.username, users.display_name AS displayname FROM users WHERE users.id = ?`;

export interface GetUserByIdArgs {
    id: any;
}

export interface GetUserByIdRow {
    id: any;
    username: any;
    displayname: any | null;
}

export async function getUserById(database: Database, args: GetUserByIdArgs): Promise<GetUserByIdRow | null> {
    const stmt = database.prepare(getUserByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetUserByIdRow;
}

export const getUserByUserNameQuery = `-- name: GetUserByUserName :one
SELECT users.id, users.username, users.display_name AS displayname FROM users WHERE users.username = ?`;

export interface GetUserByUserNameArgs {
    username: any;
}

export interface GetUserByUserNameRow {
    id: any;
    username: any;
    displayname: any | null;
}

export async function getUserByUserName(database: Database, args: GetUserByUserNameArgs): Promise<GetUserByUserNameRow | null> {
    const stmt = database.prepare(getUserByUserNameQuery);
    const result = await stmt.get(args.username);
    if (result == undefined) {
        return null;
    }
    return result as GetUserByUserNameRow;
}

export const getUserByUserNameWithPasswordQuery = `-- name: GetUserByUserNameWithPassword :one
SELECT users.id, users.username, users.user_password, users.display_name AS displayname FROM users WHERE users.username = ?`;

export interface GetUserByUserNameWithPasswordArgs {
    username: any;
}

export interface GetUserByUserNameWithPasswordRow {
    id: any;
    username: any;
    userPassword: any;
    displayname: any | null;
}

export async function getUserByUserNameWithPassword(database: Database, args: GetUserByUserNameWithPasswordArgs): Promise<GetUserByUserNameWithPasswordRow | null> {
    const stmt = database.prepare(getUserByUserNameWithPasswordQuery);
    const result = await stmt.get(args.username);
    if (result == undefined) {
        return null;
    }
    return result as GetUserByUserNameWithPasswordRow;
}

export const upsertUserQuery = `-- name: UpsertUser :one
INSERT INTO users (username, user_password, display_name) VALUES (?,?,?) RETURNING id`;

export interface UpsertUserArgs {
    username: any;
    userPassword: any;
    displayName: any | null;
}

export interface UpsertUserRow {
    id: any;
}

export async function upsertUser(database: Database, args: UpsertUserArgs): Promise<UpsertUserRow | null> {
    const stmt = database.prepare(upsertUserQuery);
    const result = await stmt.get(args.username, args.userPassword, args.displayName);
    if (result == undefined) {
        return null;
    }
    return result as UpsertUserRow;
}

export const updateDisplayNameQuery = `-- name: UpdateDisplayName :exec
UPDATE users SET display_name = ? WHERE id = ?`;

export interface UpdateDisplayNameArgs {
    displayName: any | null;
    id: any;
}

export async function updateDisplayName(database: Database, args: UpdateDisplayNameArgs): Promise<void> {
    const stmt = database.prepare(updateDisplayNameQuery);
    await stmt.run(args.displayName, args.id);
}

export const getUserCountQuery = `-- name: GetUserCount :one
SELECT COUNT(*) AS count FROM users`;

export interface GetUserCountRow {
    count: number;
}

export async function getUserCount(database: Database): Promise<GetUserCountRow | null> {
    const stmt = database.prepare(getUserCountQuery);
    const result = await stmt.get();
    if (result == undefined) {
        return null;
    }
    return result as GetUserCountRow;
}

export const deleteAllUsersQuery = `-- name: DeleteAllUsers :exec
DELETE FROM users`;

export async function deleteAllUsers(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllUsersQuery);
    await stmt.run();
}

