// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getUserQuery = `-- name: GetUser :one
SELECT "user".user_id, "user".name FROM "user" WHERE "user".user_id = ?`;

export interface GetUserArgs {
    userId: any;
}

export interface GetUserRow {
    userId: any;
    name: any;
}

export async function getUser(database: Database, args: GetUserArgs): Promise<GetUserRow | null> {
    const stmt = database.prepare(getUserQuery);
    const result = await stmt.get(args.userId);
    if (result == undefined) {
        return null;
    }
    return result as GetUserRow;
}

export const upsertUserQuery = `-- name: UpsertUser :exec
INSERT INTO "user" (user_id, name) VALUES (?, ?) ON CONFLICT(user_id) DO UPDATE SET name = excluded.name`;

export interface UpsertUserArgs {
    userId: any;
    name: any;
}

export async function upsertUser(database: Database, args: UpsertUserArgs): Promise<void> {
    const stmt = database.prepare(upsertUserQuery);
    await stmt.run(args.userId, args.name);
}

