// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getUserBySlugQuery = `-- name: GetUserBySlug :one
SELECT "user".id, "user".slug, "user".name FROM "user" WHERE "user".slug = ?`;

export interface GetUserBySlugArgs {
    slug: any;
}

export interface GetUserBySlugRow {
    id: any;
    slug: any;
    name: any;
}

export async function getUserBySlug(database: Database, args: GetUserBySlugArgs): Promise<GetUserBySlugRow | null> {
    const stmt = database.prepare(getUserBySlugQuery);
    const result = await stmt.get(args.slug);
    if (result == undefined) {
        return null;
    }
    return result as GetUserBySlugRow;
}

export const getUserByIdQuery = `-- name: GetUserById :one
SELECT "user".id, "user".slug, "user".name FROM "user" WHERE "user".id = ?`;

export interface GetUserByIdArgs {
    id: any;
}

export interface GetUserByIdRow {
    id: any;
    slug: any;
    name: any;
}

export async function getUserById(database: Database, args: GetUserByIdArgs): Promise<GetUserByIdRow | null> {
    const stmt = database.prepare(getUserByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetUserByIdRow;
}

export const upsertUserQuery = `-- name: UpsertUser :one
INSERT INTO "user" (slug, name) VALUES (?, ?) ON CONFLICT(slug) DO UPDATE SET name = excluded.name RETURNING id`;

export interface UpsertUserArgs {
    slug: any;
    name: any;
}

export interface UpsertUserRow {
    id: any;
}

export async function upsertUser(database: Database, args: UpsertUserArgs): Promise<UpsertUserRow | null> {
    const stmt = database.prepare(upsertUserQuery);
    const result = await stmt.get(args.slug, args.name);
    if (result == undefined) {
        return null;
    }
    return result as UpsertUserRow;
}

