// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getUserByIdQuery = `-- name: GetUserById :one
SELECT "user".id, "user".name FROM "user" WHERE "user".id = ?`;

export interface GetUserByIdArgs {
    id: any;
}

export interface GetUserByIdRow {
    id: any;
    name: any;
}

export async function getUserById(database: Database, args: GetUserByIdArgs): Promise<GetUserByIdRow | null> {
    const stmt = database.prepare(getUserByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetUserByIdRow;
}

export const upsertUserQuery = `-- name: UpsertUser :one
INSERT INTO "user" (name) VALUES (?) RETURNING id`;

export interface UpsertUserArgs {
    name: any;
}

export interface UpsertUserRow {
    id: any;
}

export async function upsertUser(database: Database, args: UpsertUserArgs): Promise<UpsertUserRow | null> {
    const stmt = database.prepare(upsertUserQuery);
    const result = await stmt.get(args.name);
    if (result == undefined) {
        return null;
    }
    return result as UpsertUserRow;
}

export const updateUserNameQuery = `-- name: UpdateUserName :exec
UPDATE "user" SET name = ? WHERE id = ?`;

export interface UpdateUserNameArgs {
    name: any;
    id: any;
}

export async function updateUserName(database: Database, args: UpdateUserNameArgs): Promise<void> {
    const stmt = database.prepare(updateUserNameQuery);
    await stmt.run(args.name, args.id);
}

