// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getCourseByIdQuery = `-- name: GetCourseById :one
SELECT course.id, course.slug, course.title FROM course WHERE course.id = ?`;

export interface GetCourseByIdArgs {
    id: any;
}

export interface GetCourseByIdRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCourseById(database: Database, args: GetCourseByIdArgs): Promise<GetCourseByIdRow | null> {
    const stmt = database.prepare(getCourseByIdQuery);
    const result = await stmt.get(args.id);
    if (result == undefined) {
        return null;
    }
    return result as GetCourseByIdRow;
}

export const getCourseBySlugQuery = `-- name: GetCourseBySlug :one
SELECT course.id, course.slug, course.title FROM course WHERE course.slug = ?`;

export interface GetCourseBySlugArgs {
    slug: any;
}

export interface GetCourseBySlugRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCourseBySlug(database: Database, args: GetCourseBySlugArgs): Promise<GetCourseBySlugRow | null> {
    const stmt = database.prepare(getCourseBySlugQuery);
    const result = await stmt.get(args.slug);
    if (result == undefined) {
        return null;
    }
    return result as GetCourseBySlugRow;
}

export const getAllCoursesQuery = `-- name: GetAllCourses :many
SELECT course.id, course.slug, course.title FROM course`;

export interface GetAllCoursesRow {
    id: any;
    slug: any;
    title: any;
}

export async function getAllCourses(database: Database): Promise<GetAllCoursesRow[]> {
    const stmt = database.prepare(getAllCoursesQuery);
    const result = await stmt.all();
    return result as GetAllCoursesRow[];
}

export const createCourseQuery = `-- name: CreateCourse :one
INSERT INTO course (slug, title) VALUES (?, ?) RETURNING id`;

export interface CreateCourseArgs {
    slug: any;
    title: any;
}

export interface CreateCourseRow {
    id: any;
}

export async function createCourse(database: Database, args: CreateCourseArgs): Promise<CreateCourseRow | null> {
    const stmt = database.prepare(createCourseQuery);
    const result = await stmt.get(args.slug, args.title);
    if (result == undefined) {
        return null;
    }
    return result as CreateCourseRow;
}

export const deleteAllCoursesQuery = `-- name: DeleteAllCourses :exec
DELETE FROM course`;

export async function deleteAllCourses(database: Database): Promise<void> {
    const stmt = database.prepare(deleteAllCoursesQuery);
    await stmt.run();
}

