// Code generated by sqlc. DO NOT EDIT.

import { Database } from "better-sqlite3";

export const getCourseSyncRowsQuery = `-- name: GetCourseSyncRows :many
SELECT id, slug, title FROM course`;

export interface GetCourseSyncRowsRow {
    id: any;
    slug: any;
    title: any;
}

export async function getCourseSyncRows(database: Database): Promise<GetCourseSyncRowsRow[]> {
    const stmt = database.prepare(getCourseSyncRowsQuery);
    const result = await stmt.all();
    return result as GetCourseSyncRowsRow[];
}

export const getCategorySyncRowsQuery = `-- name: GetCategorySyncRows :many
SELECT id, slug, title, course_id AS courseid FROM category`;

export interface GetCategorySyncRowsRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
}

export async function getCategorySyncRows(database: Database): Promise<GetCategorySyncRowsRow[]> {
    const stmt = database.prepare(getCategorySyncRowsQuery);
    const result = await stmt.all();
    return result as GetCategorySyncRowsRow[];
}

export const getSectionSyncRowsQuery = `-- name: GetSectionSyncRows :many
SELECT id, slug, title, course_id AS courseid, category_id AS categoryid FROM section`;

export interface GetSectionSyncRowsRow {
    id: any;
    slug: any;
    title: any;
    courseid: any;
    categoryid: any;
}

export async function getSectionSyncRows(database: Database): Promise<GetSectionSyncRowsRow[]> {
    const stmt = database.prepare(getSectionSyncRowsQuery);
    const result = await stmt.all();
    return result as GetSectionSyncRowsRow[];
}

export const getLessonSyncRowsQuery = `-- name: GetLessonSyncRows :many
SELECT id, slug, title, html, lesson_order AS lessonorder, course_id AS courseid, category_id AS categoryid, section_id AS sectionid, keywords FROM lesson`;

export interface GetLessonSyncRowsRow {
    id: any;
    slug: any;
    title: any;
    html: any;
    lessonorder: any;
    courseid: any;
    categoryid: any;
    sectionid: any;
    keywords: any;
}

export async function getLessonSyncRows(database: Database): Promise<GetLessonSyncRowsRow[]> {
    const stmt = database.prepare(getLessonSyncRowsQuery);
    const result = await stmt.all();
    return result as GetLessonSyncRowsRow[];
}

export const upsertCourseQuery = `-- name: UpsertCourse :exec
INSERT INTO course (id, slug, title) VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title`;

export interface UpsertCourseArgs {
    id: any;
    slug: any;
    title: any;
}

export async function upsertCourse(database: Database, args: UpsertCourseArgs): Promise<void> {
    const stmt = database.prepare(upsertCourseQuery);
    await stmt.run(args.id, args.slug, args.title);
}

export const upsertCategoryQuery = `-- name: UpsertCategory :exec
INSERT INTO category (id, slug, title, course_id) VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, course_id = excluded.course_id`;

export interface UpsertCategoryArgs {
    id: any;
    slug: any;
    title: any;
    courseId: any;
}

export async function upsertCategory(database: Database, args: UpsertCategoryArgs): Promise<void> {
    const stmt = database.prepare(upsertCategoryQuery);
    await stmt.run(args.id, args.slug, args.title, args.courseId);
}

export const upsertSectionQuery = `-- name: UpsertSection :exec
INSERT INTO section (id, slug, title, course_id, category_id) VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, course_id = excluded.course_id, category_id = excluded.category_id`;

export interface UpsertSectionArgs {
    id: any;
    slug: any;
    title: any;
    courseId: any;
    categoryId: any;
}

export async function upsertSection(database: Database, args: UpsertSectionArgs): Promise<void> {
    const stmt = database.prepare(upsertSectionQuery);
    await stmt.run(args.id, args.slug, args.title, args.courseId, args.categoryId);
}

export const upsertLessonQuery = `-- name: UpsertLesson :exec
INSERT INTO lesson (id, slug, title, html, lesson_order, course_id, category_id, section_id, keywords) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET slug = excluded.slug, title = excluded.title, html = excluded.html, lesson_order = excluded.lesson_order, course_id = excluded.course_id, category_id = excluded.category_id, section_id = excluded.section_id, keywords = excluded.keywords`;

export interface UpsertLessonArgs {
    id: any;
    slug: any;
    title: any;
    html: any;
    lessonOrder: any;
    courseId: any;
    categoryId: any;
    sectionId: any;
    keywords: any;
}

export async function upsertLesson(database: Database, args: UpsertLessonArgs): Promise<void> {
    const stmt = database.prepare(upsertLessonQuery);
    await stmt.run(args.id, args.slug, args.title, args.html, args.lessonOrder, args.courseId, args.categoryId, args.sectionId, args.keywords);
}

export const getLessonKeywordCountQuery = `-- name: GetLessonKeywordCount :one
SELECT COUNT(*) AS c FROM lesson WHERE keywords IS NOT NULL AND keywords != '[]'`;

export interface GetLessonKeywordCountRow {
    c: number;
}

export async function getLessonKeywordCount(database: Database): Promise<GetLessonKeywordCountRow | null> {
    const stmt = database.prepare(getLessonKeywordCountQuery);
    const result = await stmt.get();
    if (result == undefined) {
        return null;
    }
    return result as GetLessonKeywordCountRow;
}

