#!/bin/bash
# Seed the production/remote D1 database with content schema and data.
# Wipes content tables first (never users/progress), then re-inserts.
#
# Prerequisites:
#   1. A remote D1 database must exist and be wired into wrangler.jsonc
#      under env.production.d1_databases with binding D1_CONTENT.
#   2. You must be logged in to Cloudflare:
#        wrangler login
#   3. The d1-seed.sql file must exist (generated by `pnpm seed`).
#
# Usage:
#   pnpm seed:production

set -euo pipefail

echo "==> Applying D1 migrations to production..."
npx wrangler d1 migrations apply D1_CONTENT --remote --env production

echo ""
echo "==> Wiping stale content data (users & progress preserved)..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
npx wrangler d1 execute D1_CONTENT --remote --env production --file="$SCRIPT_DIR/wipe-content.sql"

echo ""
echo "==> Seeding D1 content data..."
npx wrangler d1 execute D1_CONTENT --remote --env production --file=.data/d1-seed.sql

echo ""
echo "Done. Production D1 database initialized."
