#!/bin/bash
# Apply D1 migrations and seed data to the local D1 database.
# Always produces a clean state: wipes content tables, then re-inserts.
#
# Prerequisites:
#   1. d1-seed.sql must exist (generated by `pnpm seed`).
#
# Usage:
#   pnpm seed:local

set -euo pipefail

echo "==> Applying D1 migrations to local..."
npx wrangler d1 migrations apply D1_CONTENT --local

echo ""
echo "==> Wiping stale content data..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
npx wrangler d1 execute D1_CONTENT --local --file="$SCRIPT_DIR/wipe-content.sql"

echo ""
echo "==> Seeding D1 content data..."
npx wrangler d1 execute D1_CONTENT --local --file=d1-seed.sql

echo ""
echo "Done. Local D1 database initialized."
