#!/bin/bash
# Apply D1 migrations and seed data to the local D1 database.
#
# Prerequisites:
#   1. d1-seed.sql must exist (generated by `pnpm seed`).
#
# Usage:
#   pnpm seed:d1-local

set -euo pipefail

echo "==> Applying D1 migrations to local..."
npx wrangler d1 migrations apply D1_CONTENT --local

echo ""
echo "==> Seeding D1 content data..."
npx wrangler d1 execute D1_CONTENT --local --file=d1-seed.sql

echo ""
echo "Done. Local D1 database initialized."
