#!/bin/bash
# Seed the staging/remote D1 database with content schema and data.
#
# Prerequisites:
#   1. A remote D1 database must exist and be wired into wrangler.jsonc
#      under env.staging.d1_databases with binding D1_CONTENT.
#   2. You must be logged in to Cloudflare:
#        wrangler login
#   3. The d1-seed.sql file must exist (generated by `pnpm seed`).
#
# Usage:
#   pnpm seed:d1-staging

set -euo pipefail

echo "==> Applying D1 migrations to staging..."
npx wrangler d1 migrations apply D1_CONTENT --remote --env staging

echo ""
echo "==> Seeding D1 content data..."
npx wrangler d1 execute D1_CONTENT --remote --env staging --file=d1-seed.sql

echo ""
echo "Done. Staging D1 database initialized."
