#!/bin/bash
# Apply D1 migrations and seed data to the local D1 database.
# Always produces a clean state: wipes content tables, then re-inserts.
#
# Prerequisites:
#   1. lessons.db must exist (committed to repo, or generated by `pnpm generate`).
#
# Usage:
#   pnpm seed

set -euo pipefail

echo "==> Applying D1 migrations to local..."
npx wrangler d1 migrations apply D1_CONTENT --local

echo "==> Generating D1 seed SQL from lessons.db..."
npx tsx scripts/convert-db-to-sql.ts

echo ""
echo "==> Wiping stale content data..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
npx wrangler d1 execute D1_CONTENT --local --file="$SCRIPT_DIR/wipe-content.sql"

echo ""
echo "==> Seeding D1 content data..."
for f in .data/d1-seed-*.sql; do
  npx wrangler d1 execute D1_CONTENT --local --file="$f"
done

echo ""
echo "Done. Local D1 database initialized."
